version: "3.8"
services:
  database:
    image: postgres:16
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4
  #   restart: always
  #   ports:
  #     - "5051:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin123"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

  directus:
    image: directus/directus:11.5.1
    container_name: directus
    restart: always
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./snapshots:/directus/snapshots
    depends_on:
      - database
    environment:
      KEY: "online-portfolio-key"
      SECRET: "online-portfolio-secret"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      ADMIN_EMAIL: "admin@admin.com"
      ADMIN_PASSWORD: "admin123"
      EXTENSIONS_AUTO_RELOAD: true
      EXTENSIONS_MUST_LOAD: true
      WEBSOCKETS_ENABLED: true
      CORS_ENABLED: true
      CORS_ORIGIN: "*"
      REFRESH_TOKEN_COOKIE_NAME: "refresh_token"
      IMPORT_IP_DENY_LIST: ::1,127.0.0.1
      MARKETPLACE_TRUST: "all"
      TZ: "Asia/Manila"

volumes:
  local_pgdata:
  # pgadmin-data:
